active: onnx-example
models:
  mock:
    backend: mock
    label: mock-target
  onnx-example:
    backend: onnxruntime
    model: models/yolo11n.onnx
    labels: []
    confidence: 0.25
    nms: 0.45
  rdk-example:
    backend: rdk-hbm
    model: models/yolo11n_bayese_640x640_nv12.bin
    input_size: [640, 640]
    classes_num: 9
    labels: [apple, avacado, banana, guava, kiwi, mango, orange, peach, pineapple]
    confidence: 0.25
    nms: 0.70
    reg: 16
    strides: [8, 16, 32]
    resize_type: 1
    priority: 0
    bpu_cores: [0]
